@API_HostAddress = https://localhost:7254

POST {{API_HostAddress}}/api/account/authenticate
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###

POST {{API_HostAddress}}/api/account/register-health-care-provider
Content-Type: application/json

{
  "firstName": "first",
  "lastName": "test",
  "phoneNumber": "11223344",
  "specialitiesIds": ["98ecada4-4ac5-4042-8ac1-7baf2a984d4d"],
  "localRegistrationNumber": "112233",
  "nationalRegistrationNumber": "445566",
  "email": "test@example.com",
  "emailConfirmed": "test@example.com",
  "password": "Password#123"
}

###
